update

diff --git a/Jenkinsfile.backup b/Jenkinsfile.backup
--- a/Jenkinsfile.backup
+++ b/Jenkinsfile.backup
@@ -13,12 +13,6 @@ pipeline {
         FULL_PATH_BRANCH = "${sh(script:'git name-rev --name-only HEAD', returnStdout: true)}"
         GIT_BRANCH = FULL_PATH_BRANCH.substring(FULL_PATH_BRANCH.lastIndexOf('/') + 1, FULL_PATH_BRANCH.length())
         }
- parameters {
-        string(name: 'TF_WORKSPACE', defaultValue: 'dev', description: 'Workspace (dev/prod) file to use for deployment')
-        //string(name: 'version', defaultValue: '0.13.3', description: 'Version variable to pass to Terraform')
-        booleanParam(name: 'autoApprove', defaultValue: false, description: 'Automatically run apply after generating plan?')
-    }
-
      
   stages {
         stage('Checkout') {
@@ -35,6 +29,24 @@ pipeline {
             }
         }
 
+        stage('Packer-AMI-Builder') {
+            steps {
+                script {
+                    dir('packer')
+                        {
+                        sh 'chmod +x packer-build-ami.sh'
+                        echo 'I am inside packer'
+                        def result = sh returnStatus: true, script: 'sudo ./packer-build-ami.sh'
+                        if (result != 0) {
+                            echo '[PACKER: FAILURE] Failed to build AMI'
+                            currentBuild.result = 'FAILURE'
+                            sh "exit ${result}"  
+                            }
+                        }
+                }
+            }
+        }
+
         stage('Set Terraform path') {
             steps {
                 script {  // script is used for complex scripts, loops, conditions elese use steps
@@ -47,68 +59,16 @@ pipeline {
              }
         }
  
-    stage('BuildInfo') {
-            steps {
-                    echo "Running Buid num: ${env.BUILD_ID} on Jenkins ${env.JENKINS_URL}"
-                    echo "BUILD_NUMBER :: ${env.BUILD_NUMBER}"
-                    echo "BUILD_ID :: ${env.BUILD_ID}"
-                    echo "BUILD_DISPLAY_NAME :: ${env.BUILD_DISPLAY_NAME}"
-                    echo "JOB_NAME :: ${env.JOB_NAME}"
-                    echo "JOB_BASE_NAME :: ${env.JOB_BASE_NAME}"
-                    echo "BUILD_TAG :: ${env.BUILD_TAG}"
-                    echo "EXECUTOR_NUMBER :: ${env.EXECUTOR_NUMBER}"
-                    echo "NODE_NAME :: ${env.NODE_NAME}"
-                    echo "NODE_LABELS :: ${env.NODE_LABELS}"
-                    echo "WORKSPACE :: ${env.WORKSPACE}"
-                    echo "JENKINS_HOME :: ${env.JENKINS_HOME}"
-                    echo "JENKINS_URL :: ${env.JENKINS_URL}"
-                    echo "BUILD_URL ::${env.BUILD_URL}"
-                    echo "JOB_URL :: ${env.JOB_URL}"
+    stage('Provision infrastructure') {
+         steps {
+            //dir('dev')
+            //    {
+                sh 'sudo chmod +x jenkins-run-terraform.sh'
+                sh 'sudo ./jenkins-run-terraform.sh'
+              //  }
+            }
+        }
     
-                }
-            }
-        stage('Plan') {
-            steps {
-                script {
-                    currentBuild.displayName = params.version //not required
-                }
-                //dir("${env.WORKSPACE}/Terraform-with-Jenkins"){  //directory steps paramters to change the directory(if you have terraform in a dir in git)
-                  //https://www.jenkins.io/doc/pipeline/steps/workflow-basic-steps/#dir-change-current-directory
-                  //In normal git configuration we do not require to change the directory
-                  sh 'pwd'
-                  sh 'terraform --version'
-                  sh 'terraform init -input=false'
-                  //sh 'terraform workspace select ${TF_WORKSPACE}'
-                  sh 'terraform workspace new $TF_WORKSPACE || true'
-                  sh "terraform plan -input=false -out tfplan --var-file=${params.TF_WORKSPACE}.tfvars"
-                  sh 'terraform show -no-color tfplan > tfplan.txt'
-                //}
-            }
-        }
-
-        stage('Approval') {
-            when {
-                not {
-                    equals expected: true, actual: params.autoApprove
-                }
-            }
-
-            steps {
-                script {
-                    def plan = readFile 'tfplan.txt'
-                    input message: "Do you want to apply the plan?",
-                        parameters: [text(name: 'Plan', description: 'Please review the plan', defaultValue: plan)]
-                }
-            }
-        }
-
-        stage('Apply') {
-            steps {
-                sh "terraform apply -input=false tfplan"
-                }
-        }
-
-  
         stage('Infra-Destroy') {
             input {
                 message "Should we destroy the infrastructre ?"
@@ -122,6 +82,11 @@ pipeline {
             steps {
                 echo "Hello, ${PERSON}, nice to meet you."
                 sh 'terraform destroy -auto-approve'
+                dir('packer')
+                {
+                sh 'chmod +x packer-destroy.sh'
+                sh 'sudo ./packer-destroy.sh'
+                }
             }
             when { 
                 environment name: 'INFRA-DEL', value: 'Yes'
@@ -163,3 +128,12 @@ pipeline {
                 }   
         }
 }
+
+
+                // withCredentials([
+                //     string(credentialsId: 'websearch_mysql_pwd', variable: 'MYSQL_PWD'),
+                //     string(credentialsId: 'websearch_mysql_root_pwd', variable: 'MYSQL_ROOT_PWD'),
+                //     file(credentialsId: 'AWS_PEM', variable: 'AWS_KEY')
+                //     ]) { 
+                //     echo "My password is '${MYSQL_PWD}'!"
+                //     echo "My key is '${AWS_Key}'"
